allbachelor/allbachelor/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('', views.index, name="mainpage"),
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls')),
    path('blog/', include('blog.urls')),
    path('about/', views.about, name="about"),
    url(r'^shop/', include(('shop.urls', 'shop'), namespace='shop')),
    path('profiles/', include('profiles.urls')),
    path(r'markdownx/', include('markdownx.urls')),
    path('order/', include('order.urls')),
    path('tfidf/', include('tfidf.urls')),
    path('matrixfactorization/', include('matrixfactorization.urls')),




]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

allbachelor/blog/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.index, name="bloghome"),
]

allbachelor/profiles/urls.py
from . import views
from django.conf.urls import url, include
from django.urls import path,re_path
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'profiles'


urlpatterns = [
    # path('accounts/', include('profiles.accounts.urls', namespace='accounts')),
    path('profiles/<slug:profile_slug>/change-password', views.change_password, name="change-password"),
    path('profiles/<slug:profile_slug>/edit', views.edit_profile, name="edit-profile"),
    path('profiles/<slug:profile_slug>/', views.profile, name="profile"),
    path('', views.profiles, name="profiles"),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

allbachelor/shop/urls.py
from . import views
from django.conf.urls import url, include
from django.urls import path,re_path
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'shop'


urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('login/', views.user_login, name="login"),
    path('logout/', views.user_logout, name="logout"),
    path('about/', views.about, name="about"),
    url('^', include('django.contrib.auth.urls')),
    url(r'^oauth/', include('social_django.urls', namespace="social")),
    url('product_list/', views.product_list_category, name="list"),
    url('index/', views.index, name="shophome"),
    url(r'^$', views.index, name='product_list'),
    url('search/', views.search_list, name='query'),
    # url('electronics/', views.electronics, name='query'),
    url('trending/', views.search_list, name ='query'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.product_list_category, name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
    url(r'^cat/(?P<subcategory_slug>[-\w]+)/$', views.product_list_subcategory, name='product_list_by_subcategory'),

    url('r/reviewlist/', views.review_list, name='review_list'),
    url(r'^review/(?P<review_id>[0-9]+)/$', views.review_detail, name='review_detail'),
    url(r'^product$', views.product_list, name='product_list'),
    url(r'^product/(?P<product_id>[0-9]+)/$', views.product_detail, name='product_detail'),
    url(r'^product/(?P<product_id>[0-9]+)/add_review/$', views.add_review, name='add_review'),
    url(r'^review/user/(?P<username>\w+)/$',views.user_review_list,name='user_review_list'),
    url(r'^review/user/$', views.user_review_list, name='user_review_list'),
    url('r/recommendation/', views.user_recommendation_list, name='user_recommendation_list'),



]

allbachelor/shop/forms.py
from django import forms
from django.forms import ModelForm, Textarea
from .models import Review
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.hashers import check_password
from bootstrap_datepicker_plus import DatePickerInput
from zxcvbn_password.fields import PasswordField, PasswordConfirmationField
from markdownx.fields import MarkdownxFormField
from django import forms

from django.core.validators import MinLengthValidator
from PIL import Image


class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = ['rating', 'comment']
        widgets = {
            'comment': Textarea(attrs={'cols': 20, 'rows': 5}),
        }

allbachelor/profiles/views.py
from django.contrib.auth import logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required, login_required, login_required
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import HttpResponseRedirect
import datetime
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import auth, messages
from django.contrib.auth.models import User

from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse

from shop.models import Product
from .forms import ProfileForm, CustomChangePasswordForm
from .models import Profile


def profiles(request):
    """Load Homepage via Profile Link"""
    profiles = Profile.objects.all().filter(user_id=request.user.id)
    product_list = Product.objects.order_by('-name')
    return render(request, 'profiles/index.html', {'profiles': profiles,'product_list': product_list},

                                                                        )


@login_required
def profile(request, profile_slug):
    """Load Profile"""
    profile = get_object_or_404(Profile, slug=profile_slug)
    return render(request, 'profiles/profile.html', {'profile': profile})


@login_required
def edit_profile(request, profile_slug):
    """Edit Profile Form"""
    profile = get_object_or_404(Profile, slug=profile_slug)
    form = ProfileForm(instance=profile)

    if request.method == "POST":
        form = ProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            messages.success(request, "{} {}'s profile updated."
                             .format(form.cleaned_data["first_name"],
                                     form.cleaned_data["last_name"]))
            return HttpResponseRedirect(profile.get_absolute_url())
    return render(request, "profiles/edit-profile.html", {'form': form})


@login_required
def change_password(request, profile_slug):
    """Change Password Form"""
    if request.method == 'POST':
        form = CustomChangePasswordForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was '
                                      'successfully updated!')
            return HttpResponseRedirect(reverse('index'))
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = CustomChangePasswordForm(request.user)
    return render(request, 'profiles/change-password.html', {
        'form': form
    })

allbachelor/shop/views.py
from django.contrib.auth import logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import HttpResponseRedirect
import datetime
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import auth, messages
from django.contrib.auth.models import User

from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse

from order.models import ShopCartForm
from .forms import ReviewForm
from .suggestions import update_clusters
from .models import Category, Product, SubCategory, Slider, Review, Cluster


def signup(request):
    if request.method == "POST":
        # creating a user
        if request.POST['password'] == request.POST['repeatpassword']:
            try:
                user = User.objects.get(username=request.POST['username'])
                return render(request, 'shop/Register.html', {'error': "User already exist"})
            except User.DoesNotExist:
                user = User.objects.create_user(username=request.POST['username'], password=request.POST['password'],
                                                email=request.POST['email'])

                return redirect(index)
        else:
            return render(request, 'shop/Register.html', {'error': "Password Don't match"})

    else:
        return render(request, 'shop/Register.html')


def user_login(request):
    if request.method == "POST":
        uname = request.POST['username']
        pwd = request.POST['password']
        user = auth.authenticate(username=uname, password=pwd)
        if user is not None:
            auth.login(request, user)
            return render(request, 'shop/index.html', {'error': "Invalid Login credential"})

        else:
            return render(request, 'shop/login.html', {'error': "Invalid Login credential"})
    else:
        return render(request, 'shop/login.html')


def user_logout(request):
    logout(request)
    return redirect("shop:shophome")


def index(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    slider = Slider.objects.all()
    electronics = SubCategory.objects.filter(Q(category_id=1))
    products = Product.objects.filter(available=True).order_by('-created')
    paginator = Paginator(products, 3)
    page = request.GET.get('page')
    paged_products = paginator.get_page(page)
    product_list = Product.objects.order_by('-name')

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'shop/index.html', {'category': category,
                                               'categories': categories,
                                               'slider': slider,
                                               'electronics': electronics,
                                               'product_list': product_list,
                                               'products': paged_products})


def about(request, category_slug=None):
    category = None
    categories = Category.objects.filter(Q(name="sweate"))
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'about.html', {'category': category,
                                          'categories': categories,
                                          'products': products})


def product_list_category(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    product_list = Product.objects.order_by('-name')
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        print(category)
        products = products.filter(category=category)
    return render(request, 'shop/list.html', {'category': category,
                                              'categories': categories,
                                              'products': products,
                                              'product_list': product_list})


def search_list(request):
    print(request.GET)
    method_dir = request
    query = method_dir.GET.get('q', None)
    if query is not None:
        lookups = Q(name=query) | Q(description=query)
        products = Product.objects.filter(lookups).distinct()
    else:
        products = Product.objects.none()

    print(products)

    return render(request, 'shop/searchview.html', {'products': products})


def product_list_subcategory(request, subcategory_slug=None):
    subcategories = SubCategory.objects.all()
    products = Product.objects.filter(available=True)
    if subcategory_slug:
        subcategory = get_object_or_404(SubCategory, slug=subcategory_slug)
        print(subcategory)
        products = products.filter(subCategory=subcategory)
    return render(request, 'shop/list.html', {'subcategory': subcategory,
                                              'subcategories': subcategories,
                                              'products': products})


# def product_detail(request, id, slug):
#     product = get_object_or_404(Product, id=id, slug=slug, available=True)
#     # cart_product_form = CartAddProductForm()
#     return render(request,
#                   'shop/show.html',
#                   {'product': product})


# for recommendation

def review_list(request):
    latest_review_list = Review.objects.order_by('-pub_date')[:9]
    context = {'latest_review_list': latest_review_list}
    return render(request, 'shop/review_list.html', context)


def review_detail(request, review_id):
    review = get_object_or_404(Review, pk=review_id)
    return render(request, 'shop/review_detail.html', {'review': review})


def product_list(request):
    product_list = Product.objects.order_by('-name')
    context = {'product_list': product_list}
    return render(request, 'shop/product_list.html', context)


def product_detail(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    form = ReviewForm()
    form = ShopCartForm()
    return render(request, 'shop/product_detail.html', {'product': product, 'form': form})


@login_required
def add_review(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    form = ReviewForm(request.POST)
    if form.is_valid():
        rating = form.cleaned_data['rating']
        comment = form.cleaned_data['comment']
        user_name = request.user.username
        review = Review()
        review.product = product
        review.user_name = user_name
        review.rating = rating
        review.comment = comment
        review.pub_date = datetime.datetime.now()
        review.save()
        update_clusters(is_new_user=False)

        return HttpResponseRedirect(reverse('shop:product_detail', args=(product.id,)))

    return render(request, 'shop/product_detail.html', {'product': product, 'form': form})


def user_review_list(request, username=None):
    if not username:
        username = request.user.username
    latest_review_list = Review.objects.filter(user_name=username).order_by('-pub_date')
    context = {'latest_review_list': latest_review_list, 'username': username}
    return render(request, 'shop/user_review_list.html', context)


@login_required
def user_recommendation_list(request):
    # get request user reviewed products
    user_reviews = Review.objects.filter(user_name=request.user.username).prefetch_related('product')
    user_reviews_product_ids = set(map(lambda x: x.product.id, user_reviews))

    # get request user cluster name (just the first one right now)
    try:
        user_cluster_name = \
            User.objects.get(username=request.user.username).cluster_set.first().name
    except:  # if no cluster assigned for a user, update clusters
        update_clusters(is_new_user=True)
        user_cluster_name = \
            User.objects.get(username=request.user.username).cluster_set.first().name

    # get usernames for other memebers of the cluster
    user_cluster_other_members = \
        Cluster.objects.get(name=user_cluster_name).users \
            .exclude(username=request.user.username).all()
    other_members_usernames = set(map(lambda x: x.username, user_cluster_other_members))

    # get reviews by those users, excluding product reviewed by the request user
    other_users_reviews = \
        Review.objects.filter(user_name__in=other_members_usernames) \
            .exclude(product__id__in=user_reviews_product_ids)
    other_users_reviews_product_ids = set(map(lambda x: x.product.id, other_users_reviews))

    # then get a product list including the previous IDs, order by rating
    product_list = sorted(
        list(Product.objects.filter(id__in=other_users_reviews_product_ids)),
        key=lambda x: x.average_rating(),
        reverse=True
    )

    return render(
        request,
        'shop/user_recommendation_list.html',
        {'username': request.user.username, 'product_list': product_list}
    )

allbachelor/shop/templates/shop/about.html
	 <h3>Categories</h3>


				 {% for c in categories %}
    <li {% if category.slug == c.slug %} {%endif %}>
        <a href ="{{ c.get_absolute_url }}">{{c.name}}</a>
        {{c.id}}
        {{c.slug}}
    </li>

	{% endfor %}

allbachelor/shop/templates/shop/list.html
{% extends 'shop/base.html' %}
{% load staticfiles %}
{% load static markdown_deux_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
{% block css %}
<link href="{%static 'profiles/css/profiles.css' %}" rel="stylesheet">
  {% endblock %}
  </head>
<!-- START MAIN -->
<body>

  {% block body %}
<center><h1> {%if category %}{{ category.name}}{% else %}{% endif %}</h1></center>
<center><h1>{%if subcategory %}{{ subcategory.name}}{% else %}{% endif %}</h1></center>
{% for product in products %}
    <div class="container">

        <div class="gallery">
{% if product_list %}
{% for product in product_list %}
            <a href="{% url 'shop:product_detail' product.id %}">
            <div class="gallery-item" tabindex="0">

              {{ product.name }}

                <img src="{{product.image.url}}"  class="gallery-image" alt="">

                <div class="gallery-item-info">

                    <ul>
                        <li class="gallery-item-likes"><i class="fas fa-star" aria-hidden="true"></i>{{ product.average_rating | floatformat }} average rating</li>
                        <li class="gallery-item-comments"><i class="fas fa-comment" aria-hidden="true"></i> {{ product.review_set.count }} reviews</li>
                    </ul>

                </div>

            </div>
                </a>
          {% endfor %}
          {% else %}
    <p>No products are available.</p>
{% endif %}
<div class="loader"></div>
        </div>
    </div>
</body>
{% endfor %}

{% endblock %}

allbachelor/shop/templates/shop/login.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
     <link href="{%static 'shop/css/login.css' %}" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Poppins:600&display=swap" rel="stylesheet">
	<script src="https://kit.fontawesome.com/a81368914c.js"></script>
	<meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>
{% if error %}
<h4>{{ error }}</h4>
{% endif %}
	<img class="wave" src="{%static 'shop/images/wave.png' %}">
	<div class="container">
		<div class="img">
	{% if error %}
<h4 style="color:red">{{ error }}</h4>
{% endif %}
		</div>
		<div class="login-content">
 <form method="POST" >
         {% csrf_token %}

				<img src="{%static 'shop/images/avatar.svg' %}">
				<h2 class="title">Welcome Back</h2>
           		<div class="input-div one">
           		   <div class="i">
           		   		<i class="fas fa-user"></i>
           		   </div>
           		   <div class="div">
           		   		<h5>Username</h5>
           		   		<input type="text" name="username" class="input" />

           		   </div>
           		</div>
           		<div class="input-div pass">
           		   <div class="i">
           		    	<i class="fas fa-lock"></i>
           		   </div>
           		   <div class="div">
           		    	<h5>Password</h5>
           		    	<input type="password" name="password" class="input"/>
            	   </div>
            	</div>
            	 <a href="shop:signup">Want to sign up with email? Sign Up</a>
            	<input type="submit" name="submit" class="btn" value="submit">
            </form>

        </div>
    </div>
   <script type="text/javascript" src="{%static 'shop/js/main.js' %}"></script>
</body>
</html>

allbachelor/shop/templates/shop/order_summary.html
  <main>
    <div class="container">

    <div class="table-responsive text-nowrap">
    <h2>Order Summary</h2>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Item title</th>
            <th scope="col">Price</th>
            <th scope="col">Quantity</th>
            <th scope="col">Total Item Price</th>
        </tr>
        </thead>
        <tbody>
        {% for order_item in object.products.all %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ order_item.item.name }}</td>
            <td>{{ order_item.item.price }}</td>
            <td>
                <a href="{%  url 'remove-single-item-from-cart' order_item.item.slug %}"><i class="fas fa-minus mr-2"></i></a>
                {{ order_item.quantity }}
                <a href="{% url 'add-to-cart' order_item.item.slug %}"><i class="fas fa-plus ml-2"></i></a>
            </td>
            <td>
            {% if order_item.item.discount_price %}
                ${{ order_item.get_total_discount_item_price }}
                <span class="badge badge-primary">Saving ${{ order_item.get_amount_saved }}</span>
            {% else %}
                ${{ order_item.get_total_item_price }}
            {% endif %}
            <a style='color: red;' href="{% url 'remove-from-cart' order_item.item.slug %}">
                <i class="fas fa-trash float-right"></i>
            </a>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan='5'>Your cart is empty</td>
        </tr>
        <tr>
            <td colspan="5">
            <a class='btn btn-primary float-right' href='/'>Continue shopping</a>
            </td>
        </tr>

        {% endfor %}

        {% if object.coupon %}
        <tr>
            <td colspan="4"><b>Coupon</b></td>
            <td><b>-${{ object.coupon.amount }}</b></td>
        </tr>
        {% endif %}
        {% if object.get_total %}
        <tr>
            <td colspan="4"><b>Order Total</b></td>
            <td><b>${{ object.get_total }}</b></td>
        </tr>
        <tr>
            <td colspan="5">
            <a class='btn btn-warning float-right ml-2' href='/checkout/'>Proceed to checkout</a>
            <a class='btn btn-primary float-right' href='/'>Continue shopping</a>
            </td>
        </tr>
        {% endif %}
        </tbody>
    </table>

    </div>

    </div>
  </main>

{% endblock content %}

allbachelor/shop/templates/shop/product_list.html
{% extends 'shop/base.html' %}
{% load staticfiles %}
{% load static markdown_deux_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
{% block css %}
<link href="{%static 'profiles/css/profiles.css' %}" rel="stylesheet">
  {% endblock %}
  </head>
<!-- START MAIN -->
<body>

  {% block body %}


    <div class="container">

        <div class="gallery">
{% if product_list %}
{% for product in product_list %}
            <a href="{% url 'shop:product_detail' product.id %}">
            <div class="gallery-item" tabindex="0">

              {{ product.name }}

                <img src="{{product.image.url}}"  class="gallery-image" alt="">

                <div class="gallery-item-info">

                    <ul>
                        <li class="gallery-item-likes"><i class="fas fa-star" aria-hidden="true"></i>{{ product.average_rating | floatformat }} average rating</li>
                        <li class="gallery-item-comments"><i class="fas fa-comment" aria-hidden="true"></i> {{ product.review_set.count }} reviews</li>
                    </ul>
                </div>

            </div>
                </a>
          {% endfor %}
          {% else %}
    <p>No products are available.</p>
{% endif %}
<div class="loader"></div>
        </div>
    </div>
</body>


{% endblock %}

allbachelor/shop/templates/shop/profile.html
{% extends 'base.html' %}
{% load static markdown_deux_tags %}

{% block css %}

    <style>
        #avatar {
            margin-bottom: 20px;
        }
        h5.bio {
            font-size: 40px;
        }
    </style>

{% endblock %}


{% block body %}

    <article>
        <div class="container" id="avatar">
            <div class="row">
                <div class="col-md-6">
                    {% if profile.avatar %}
                        <img src="{{ MEDIA_URL }}{{ profile.avatar }}" alt="{{ profile.first_name }} {{ profile.last_name }}">
                    {% endif %}
                </div>
                <div class="col-md-6">
                    <h1>Name: {{ profile.first_name }} {{ profile.last_name }}</h1>
                    <h2>Email: {{ profile.email }}</h2>
                    <p>Date of Birth: {{ profile.date_of_birth }}</p>
                </div>
            </div>
        </div>
    </article>

    <article>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h5 class="bio">BIO</h5>
                    <hr>
                    <p>{{ profile.display_bio|markdown }}</p>
                    <hr>
                    {% if profile.city %}
                        <p>City: {{ profile.city }}</p>
                    {% endif %}
                    {% if profile.state %}
                        <p>State: {{ profile.state }}</p>
                    {% endif %}
                    {% if profile.country_of_residence %}
                        <p>Country: {{ profile.country_of_residence }}</p>
                    {% endif %}
                    {% if profile.favorite_animal %}
                        <p>Animal: {{ profile.favorite_animal }}</p>
                    {% endif %}
                    {% if profile.hobby %}
                        <p>Hobby: {{ profile.hobby }}</p>
                    {% endif %}
                </div>
            </div>
        </div>
    </article>

    <a href="{% url "edit-profile" profile.slug %}" class="button">Edit</a>
    <a href="{% url "change-password" profile.slug %}" class="button">Change Password</a>

{% endblock %}

allbachelor/shop/templates/shop/review_detail.html
{% block title %}
<h2><a href="{% url 'shop:product_detail' review.product.id %}">{{ review.product.name }}</a></h2>
{% endblock %}

{% block content %}
<h4>Rated {{ review.rating }} of 5 by <a href="{% url 'shop:user_review_list' review.user_name %}" >{{ review.user_name }}</a></h4>
<p>{{ review.pub_date }}</p>
<p>{{ review.comment }}</p>
{% endblock %}

allbachelor/shop/templates/shop/review_list.html
{% block title %}
<h2>Latest reviews</h2>
{% endblock %}

{% block content %}
{% if latest_review_list %}
<div class="row">
    {% for review in latest_review_list %}
    <div class="col-xs-6 col-lg-4">
        <h4><a href="{% url 'shop:review_detail' review.id %}">
        {{ review.product.name }}
        </a></h4>
        <h6>Rated {{ review.rating }} of 5 by <a href="{% url 'shop:user_review_list' review.user_name %}" >{{ review.user_name }}</a></h6>
        <p>{{ review.comment }}</p>
        review.id
    </div>
    {% endfor %}
</div>
{% else %}
<p>No reviews are available.</p>
{% endif %}
{% endblock %}

allbachelor/shop/templates/shop/subcategory.html
{% load static %}
<!DOCTYPE html>
<html lang="en" >
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="{% static 'shop/css/bootstrap.css' %}" rel="stylesheet" type="text/css" media="all" />
	<!-- Bootstrap css -->
	<link href="{% static 'shop/css/style.css' %}" rel="stylesheet" type="text/css" media="all" />
	<!-- Main css -->
	<link rel="stylesheet" href="{% static 'shop/css/fontawesome-all.css' %}">
	<!-- Font-Awesome-Icons-CSS -->
	<link href="{% static 'shop/css/popuo-box.css' %}" rel="stylesheet" type="text/css" media="all" />
	<!-- pop-up-box -->
	<link href="{% static 'shop/css/menu.css' %}" rel="stylesheet" type="text/css" media="all" />
	<!-- menu style -->

	<link href="{% static 'shop/css/owl.carousel.css' %}" rel="stylesheet" type="text/css" media="all">
	<!-- //Custom-Files -->

	<!-- matrixfactorization fonts -->
	<link href="//fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i&amp;subset=latin-ext" rel="stylesheet">
	<link href="//fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i&amp;subset=cyrillic,cyrillic-ext,greek,greek-ext,latin-ext,vietnamese"
	    rel="stylesheet">

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<link href="https://fonts.googleapis.com/css?family=Josefin+Sans:300,400,700&subset=latin-ext" rel="stylesheet">
</head>
<body>

<h1> {%if category %}{{ category.name}}{% else %}Products{% endif %}</h1>
<div class="row">
		{% for product in products %}
<a href="{{product.get_absolute_url }}">
        <div class="col-md-3 col-sm-6">
            <div class="product-grid2">
                <div class="product-image2">
                    <a href="#">
                        <img class="pic-1" src="{{ product.image.url }}">
                        <img class="pic-2" src="{{ product.image.url }}">
                    </a>
                    <ul class="social">
                        <li><a href="#" data-tip="Quick View"><i class="fa fa-eye"></i></a></li>
                        <li><a href="#" data-tip="Add to Wishlist"><i class="fa fa-shopping-bag"></i></a></li>
                        <li><a href="#" data-tip="Add to Cart"><i class="fa fa-shopping-cart"></i></a></li>
                    </ul>
                    <a class="add-to-cart" href="">Add to cart</a>
                </div>
                <div class="product-content">
                    <h3 class="title"><a href="{{ product.get_absolute_url }}">{{product.name }}</a></h3>
                    <span class="price">{{product.price}}</span>
                    {{product.subcategory}}
                </div>
            </div>

        </div>
	{% endfor %}





</body>
</html>

allbachelor/shop/templates/shop/trending.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="col-10 agileits_search">
							<form class="form-inline" action='{% url "shop:query" %}' method="GET">
								<input class="form-control mr-sm-2" name="q" type="search" placeholder="Search" aria-label="Search" required>
								<button class="btn my-2 my-sm-0" type="submit">Search</button>
							</form>
						</div>

</body>
</html>

allbachelor/shop/templates/shop/user_recommendation_list.html
{% extends 'shop/product_list.html' %}

{% block title %}
<h2>Recommendations for {{ username }}</h2>
{% endblock %}