allbachelor/allbachelor/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('', views.index, name="mainpage"),
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls')),
    path('blog/', include('blog.urls')),
    path('about/', views.about, name="about"),
    url(r'^shop/', include(('shop.urls', 'shop'), namespace='shop')),
    path('profiles/', include('profiles.urls')),
    path(r'markdownx/', include('markdownx.urls')),
    path('order/', include('order.urls')),
    path('tfidf/', include('tfidf.urls')),
    path('matrixfactorization/', include('matrixfactorization.urls')),




]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

allbachelor/blog/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.index, name="bloghome"),
]

allbachelor/profiles/urls.py
from . import views
from django.conf.urls import url, include
from django.urls import path,re_path
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'profiles'


urlpatterns = [
    # path('accounts/', include('profiles.accounts.urls', namespace='accounts')),
    path('profiles/<slug:profile_slug>/change-password', views.change_password, name="change-password"),
    path('profiles/<slug:profile_slug>/edit', views.edit_profile, name="edit-profile"),
    path('profiles/<slug:profile_slug>/', views.profile, name="profile"),
    path('', views.profiles, name="profiles"),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

allbachelor/shop/urls.py
from . import views
from django.conf.urls import url, include
from django.urls import path,re_path
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'shop'


urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('login/', views.user_login, name="login"),
    path('logout/', views.user_logout, name="logout"),
    path('about/', views.about, name="about"),
    url('^', include('django.contrib.auth.urls')),
    url(r'^oauth/', include('social_django.urls', namespace="social")),
    url('product_list/', views.product_list_category, name="list"),
    url('index/', views.index, name="shophome"),
    url(r'^$', views.index, name='product_list'),
    url('search/', views.search_list, name='query'),
    # url('electronics/', views.electronics, name='query'),
    url('trending/', views.search_list, name ='query'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.product_list_category, name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
    url(r'^cat/(?P<subcategory_slug>[-\w]+)/$', views.product_list_subcategory, name='product_list_by_subcategory'),

    url('r/reviewlist/', views.review_list, name='review_list'),
    url(r'^review/(?P<review_id>[0-9]+)/$', views.review_detail, name='review_detail'),
    url(r'^product$', views.product_list, name='product_list'),
    url(r'^product/(?P<product_id>[0-9]+)/$', views.product_detail, name='product_detail'),
    url(r'^product/(?P<product_id>[0-9]+)/add_review/$', views.add_review, name='add_review'),
    url(r'^review/user/(?P<username>\w+)/$',views.user_review_list,name='user_review_list'),
    url(r'^review/user/$', views.user_review_list, name='user_review_list'),
    url('r/recommendation/', views.user_recommendation_list, name='user_recommendation_list'),



]

allbachelor/profiles/models.py
from Lib.enum import auto
from django.utils.safestring import mark_safe
from django.utils.text import slugify

from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


#profile info

class Profile(models.Model):
    """Profile Model"""
    # pub_date = models.DateTimeField(default=timezone.now)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(default='', max_length=50, blank=True)
    last_name = models.CharField(default='', max_length=100, blank=True)
    email = models.EmailField(max_length=100, blank=True, null=True)
    email_verify = models.EmailField(max_length=100, blank=True, null=True)
    date_of_birth = models.DateField(max_length=12, blank=True, null=True)
    bio = models.TextField(blank=True)
    avatar = models.ImageField(blank=True, upload_to='avatar')
    city = models.CharField(max_length=255, blank=True)
    district = models.CharField(max_length=255, blank=True)
    country_of_residence = models.CharField(max_length=255, blank=True)
    hobby = models.CharField(max_length=255, blank=True)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.first_name or self.last_name:
            self.slug = slugify("{}-{}-{}".format(self.first_name.lower(),
                                                  self.last_name.lower(), self.id))
        else:
            self.slug = slugify('profiles:profile {}'.format(self.id))
        super().save()

    def __str__(self):
        return "{} {}".format(self.first_name, self.last_name)

    def get_absolute_url(self):
        return reverse('profiles:profile', args=[str(self.slug)])

    def display_bio(self):
        return mark_safe(self.bio)

allbachelor/profiles/forms.py
from django import forms
from django.forms import ModelForm, Textarea

from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.hashers import check_password
from bootstrap_datepicker_plus import DatePickerInput
from zxcvbn_password.fields import PasswordField, PasswordConfirmationField
from markdownx.fields import MarkdownxFormField
from django import forms
from .models import Profile
from django.core.validators import MinLengthValidator
from PIL import Image



class ProfileForm(forms.ModelForm):
    """Profile Form + Fields for Photo Processing"""
    x = forms.FloatField(widget=forms.HiddenInput(), required=False)
    y = forms.FloatField(widget=forms.HiddenInput(), required=False)
    width = forms.FloatField(widget=forms.HiddenInput(), required=False)
    height = forms.FloatField(widget=forms.HiddenInput(), required=False)
    bio = MarkdownxFormField(validators=[MinLengthValidator(10)])

    class Meta:
        model = Profile
        fields = [
            'first_name',
            'last_name',
            'email',
            'email_verify',
            'date_of_birth',
            'bio',
            'city',
            'district',
            'country_of_residence',
            'hobby',
            'avatar',
            'x',
            'y',
            'width',
            'height',
        ]
        widgets = {
            # default date-format %m/%d/%Y will be used
            'date_of_birth': DatePickerInput(),
        }

    def clean(self):
        """Clean the whole form"""
        cleaned_data = super().clean()
        email = cleaned_data.get('email')
        verify = cleaned_data.get('email_verify')

        if email != verify:
            raise forms.ValidationError('Emails do not match')

    def save(self):
        """Override the Save method for saving the crop photo"""
        photo = super().save()

        x = self.cleaned_data.get('x')
        y = self.cleaned_data.get('y')
        w = self.cleaned_data.get('width')
        h = self.cleaned_data.get('height')

        if x is not None:
            image = Image.open(photo.avatar)
            cropped_image = image.crop((x, y, w + x, h + y))
            resized_image = cropped_image.resize((200, 200), Image.ANTIALIAS)
            resized_image.save(photo.avatar.path)
        return photo


class CustomChangePasswordForm(PasswordChangeForm):
    """Extending Password Change Form
    Overriding help_text

    """
    new_password1 = PasswordField()
    new_password2 = PasswordConfirmationField(confirm_with="new_password1")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # help_text = "<ul>" \
        #             "<li>Your password can't be too similar to " \
        #             "your other personal information</li>" \
        #             "<li>Your password must contain " \
        #             "at least 14 characters</li>" \
        #             "<li>Your password can't be a " \
        #             "commonly used password</li>" \
        #             "<li>Your password can't be " \
        #             "entirely numeric</li>" \
        #             "<li>Your password must not be " \
        #             "the same as the current password</li>" \
        #             "<li>Your password must use of " \
        #             "both uppercase and lowercase letters</li>" \
        #             "<li>Your password must include " \
        #             "of one or more numerical digits</li>" \
        #             "<li>Your password must include " \
        #             "of special characters, such as @, #, $</li>" \
        #             "</ul>"
        # self.fields['new_password1'].help_text = help_text

    class Meta:
        fields = [
            'old_password',
            'new_password1',
            'new_password2',
        ]

    def clean(self):
        """Clean is first in order not to have not matched
        error if other validation fails
        """
        cleaned_data = super().clean()
        new_password1 = cleaned_data.get('new_password1')
        new_password2 = cleaned_data.get('new_password2')

        if new_password1 != new_password2:
            raise forms.ValidationError('Your new password and '
                                        'confirmation do not match')

    def clean_new_password1(self):
        """Validating the Password1 Field"""
        new_password1 = self.cleaned_data.get('new_password1')
        new_password2 = self.cleaned_data.get('new_password2')

        if check_password(new_password1, self.user.password):
            raise forms.ValidationError('Your password must not be '
                                        'the same as the current password')

        characters = set(new_password1)

        lower = any(letter.islower() for letter in characters)
        upper = any(letter.isupper() for letter in characters)
        digit = any(letter.isdigit() for letter in characters)

        if not upper:
            raise forms.ValidationError('Your password must use of '
                                        'both uppercase and lowercase letters')

        if not lower:
            raise forms.ValidationError('Your password must use of '
                                        'both uppercase and lowercase letters')

        if not digit:
            raise forms.ValidationError('Your password must include '
                                        'of one or more numerical digits')

        special_characters = ["@", "#", "$"]
        check = False
        for character in special_characters:
            if character in new_password1:
                check = True

        if not check:
            raise forms.ValidationError('Your password must include of '
                                        'special characters, such as @, #, $')

        first_name = self.user.profile.first_name.lower()
        last_name = self.user.profile.last_name.lower()

        if first_name in new_password1.lower():
            raise forms.ValidationError('Your password cannot be too '
                                        'similar to your other personal '
                                        'information')

        if last_name in new_password1.lower():
            raise forms.ValidationError('Your password cannot be too '
                                        'similar to your other personal '
                                        'information')

        return new_password1

allbachelor/profiles/views.py
from django.contrib.auth import logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required, login_required, login_required
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import HttpResponseRedirect
import datetime
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import auth, messages
from django.contrib.auth.models import User

from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse

from shop.models import Product
from .forms import ProfileForm, CustomChangePasswordForm
from .models import Profile


def profiles(request):
    """Load Homepage via Profile Link"""
    profiles = Profile.objects.all().filter(user_id=request.user.id)
    product_list = Product.objects.order_by('-name')
    return render(request, 'profiles/index.html', {'profiles': profiles,'product_list': product_list},

                                                                        )


@login_required
def profile(request, profile_slug):
    """Load Profile"""
    profile = get_object_or_404(Profile, slug=profile_slug)
    return render(request, 'profiles/profile.html', {'profile': profile})


@login_required
def edit_profile(request, profile_slug):
    """Edit Profile Form"""
    profile = get_object_or_404(Profile, slug=profile_slug)
    form = ProfileForm(instance=profile)

    if request.method == "POST":
        form = ProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            messages.success(request, "{} {}'s profile updated."
                             .format(form.cleaned_data["first_name"],
                                     form.cleaned_data["last_name"]))
            return HttpResponseRedirect(profile.get_absolute_url())
    return render(request, "profiles/edit-profile.html", {'form': form})


@login_required
def change_password(request, profile_slug):
    """Change Password Form"""
    if request.method == 'POST':
        form = CustomChangePasswordForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was '
                                      'successfully updated!')
            return HttpResponseRedirect(reverse('index'))
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = CustomChangePasswordForm(request.user)
    return render(request, 'profiles/change-password.html', {
        'form': form
    })

allbachelor/profiles/templates/profiles/change-password.html
{% extends 'shop/base.html' %}
{% load static %}

{% block css %}

    <style>
        .progress-bar-warning {
            background-color: yellow;
        }

        .progress-bar-danger {
            background-color: red;
        }

        .progress-bar-success {
            background-color: green;
        }

        .errorlist li {
            color: red;
        }
        .helptext li {
            color: green;
        }
    </style>
<link rel="stylesheet" href="{% static 'profiles/css/global.css' %}">

{% endblock %}

{% block body %}

    <h1>Change {{ profile.first_name }} {{ profile.last_name }} Password</h1>
    <form role="form" method="POST" action="">
        {% csrf_token %}
        {{ form }}
        <input type="submit" class="button" value="Save">
    </form>

{% endblock %}

allbachelor/profiles/templates/profiles/edit-profile.html
{% extends 'profiles/base.html' %}
{% load static markdown_deux_tags %}

{% block css %}

    <link rel="stylesheet" href="{% static 'profiles/cropper/cropper.min.css' %}">
  <link rel="stylesheet" href="{% static 'profiles/css/global.css' %}">

{% endblock %}

{% block body %}



    <h1>Edit {{ profile.first_name }} {{ profile.last_name }} Profile</h1>
    <form method="POST" enctype="multipart/form-data" action="" id="formUpload">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="button" value="Save">
    </form>

    <!-- MODAL TO CROP THE IMAGE -->
      <div class="modal fade" id="modalCrop">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
              <h4 class="modal-title">Crop the photo</h4>
            </div>
            <div class="modal-body">
              <img src="" id="image" style="max-width: 100%;">
            </div>
            <div class="modal-footer">
              <div class="btn-group pull-left" role="group">
                <button type="button" class="btn btn-default js-zoom-in">
                  <span class="glyphicon glyphicon-zoom-in"></span>
                </button>
                <button type="button" class="btn btn-default js-zoom-out">
                  <span class="glyphicon glyphicon-zoom-out"></span>
                </button>
              </div>
              <button type="button" class="btn btn-default" data-dismiss="modal">Nevermind</button>
              <button type="button" class="btn btn-primary js-crop-and-upload">Crop and upload</button>
            </div>
          </div>
        </div>
      </div>

    <!-- CONTAINER TO DISPLAY THE CROPPED IMAGES -->
      <div class="row" style="margin-top: 20px">
        {% for photo in photos %}
          <div class="col-sm-4 col-md-3">
            <img src="{{ photo.file.url }}" class="thumbnail">
          </div>
        {% endfor %}
      </div>



{% endblock %}


{% block js %}

    <script type="text/javascript" src="{% static 'cropper/cropper.min.js' %}"></script>

    <script>
    $(function () {

      /* SCRIPT TO OPEN THE MODAL WITH THE PREVIEW */
      $("#id_avatar").change(function () {
        if (this.files && this.files[0]) {
          var reader = new FileReader();
          reader.onload = function (e) {
            $("#image").attr("src", e.target.result);
            $("#modalCrop").modal("show");
          }
          reader.readAsDataURL(this.files[0]);
        }
      });

      /* SCRIPTS TO HANDLE THE CROPPER BOX */
      var $image = $("#image");
      var cropBoxData;
      var canvasData;
      $("#modalCrop").on("shown.bs.modal", function () {
        $image.cropper({
          viewMode: 1,
          aspectRatio: 1/1,
          minCropBoxWidth: 200,
          minCropBoxHeight: 200,
          ready: function () {
            $image.cropper("setCanvasData", canvasData);
            $image.cropper("setCropBoxData", cropBoxData);
          }
        });
      }).on("hidden.bs.modal", function () {
        cropBoxData = $image.cropper("getCropBoxData");
        canvasData = $image.cropper("getCanvasData");
        $image.cropper("destroy");
      });

      $(".js-zoom-in").click(function () {
        $image.cropper("zoom", 0.1);
      });

      $(".js-zoom-out").click(function () {
        $image.cropper("zoom", -0.1);
      });

      /* SCRIPT TO COLLECT THE DATA AND POST TO THE SERVER */
      $(".js-crop-and-upload").click(function () {
        var cropData = $image.cropper("getData");
        $("#id_x").val(cropData["x"]);
        $("#id_y").val(cropData["y"]);
        $("#id_height").val(cropData["height"]);
        $("#id_width").val(cropData["width"]);
        $("#formUpload").submit();
      });

    });
  </script>
<script type="text/javascript"
            src="https://code.jquery.com/jquery-2.2.0.min.js"></script>
    <script type="text/javascript"
            src="{% static 'profiles/js/autogrow.js' %}"></script>
    <script type="text/javascript" src="{% static 'profiles/js/global.js' %}"></script>

    <link href="{% static 'profiles/bootstrap/css/bootstrap.css' %}" rel="stylesheet" type="text/css"/>
    <script src="{% static 'profiles/bootstrap/js/bootstrap.js' %}"></script>
    {{ form.media }}

{% endblock %}

allbachelor/profiles/templates/profiles/index.html
{% extends 'profiles/base.html' %}
{% load staticfiles %}
{% load static markdown_deux_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
{% block css %}
<link href="{%static 'profiles/css/profiles.css' %}" rel="stylesheet">
  {% endblock %}
  </head>
<!-- START MAIN -->
<body>

  {% block body %}
<header>
  {% if profiles %}
        {% for profile in profiles %}
    <div class="container">
        <div class="profile">
            <div class="profile-image">
{% if profile.avatar %}
                <img src="{{ profile.avatar.url }}" alt="{{ profile.first_name }} {{ profile.last_name }}" width="80%" height="80%">
  {% endif %}
            </div>
            <div class="profile-user-settings">
              <a href="{{ profile.get_absolute_url }}">  <h5 class="profile-user-name" style="color:black; "><b>{{ profile.first_name }} {{ profile.last_name }}</b></h5></a>

          <button class="btn btn-outline-primary" >
            <a href="{% url 'profiles:edit-profile' profile.slug %}">Edit <i class="fas fa-cog" aria-hidden="true"></i></a>
          </button>
           <button class="btn btn-outline-primary"> <a href="{% url 'profiles:change-password' profile.slug %}" class="button">Change Password</a></button>


            </div>

            <div class="profile-stats">
              </h2>
              <p style="color:black">{{ profile.email }}{% if profile.city %}| {{ profile.city }} {% endif %}| {% if profile.country_of_residence %}
                         {{ profile.country_of_residence }}</p>
                    {% endif %}</p>

                <ul>
                    <li><span class="profile-stat-count">DOB:</span>{{ profile.date_of_birth }} </li>
                   {% if profile.hobby %}

                    <li><span class="profile-stat-count">Hobby:</span>  {{ profile.hobby }}</li>
                   {% endif %}
                </ul>

            </div>
            <div class="profile-bio">
              {{ profile.display_bio|markdown }}
                </p>


            </div>

        </div>
        <!-- End of profile section -->

    </div>
    <!-- End of container -->

</header>

<main>

    <div class="container">

        <div class="gallery">
{% if product_list %}

{% for product in product_list %}
            <a href="{% url 'shop:product_detail' product.id %}">
            <div class="gallery-item" tabindex="0">

              {{ product.name }}

                <img src="{{product.image.url}}"  class="gallery-image" alt="">

                <div class="gallery-item-info">

                    <ul>
                        <li class="gallery-item-likes"><i class="fas fa-star" aria-hidden="true"></i>{{ product.average_rating | floatformat }} average rating</li>
                        <li class="gallery-item-comments"><i class="fas fa-comment" aria-hidden="true"></i> {{ product.review_set.count }} reviews</li>
                    </ul>

                </div>

            </div>
                </a>
          {% endfor %}
          {% else %}
    <p>No products are available.</p>
{% endif %}
<div class="loader"></div>
        </div>
</body>
{% endfor %}
    {% else %}
        <p>No Profile</p>
please sign in or sign up
    {% endif %}
{% endblock %}

allbachelor/profiles/templates/profiles/profile.html
{% extends 'profiles/base.html' %}
{% load static markdown_deux_tags %}

{% block css %}

    <style>
        #avatar {
            margin-bottom: 20px;
        }
        h5.bio {
            font-size: 40px;
        }
    </style>

{% endblock %}


{% block body %}

    <article>
        <div class="container" id="avatar">
            <div class="row">
                <div class="col-md-6">
                    {% if profile.avatar %}
                        <img height="50px" src="{{ profile.avatar.url }}" alt="{{ profile.first_name }} {{ profile.last_name }}">
                    {% endif %}
                </div>
                <div class="col-md-6">
                    <h1>Name: {{ profile.first_name }} {{ profile.last_name }}</h1>
                    <h2>Email: {{ profile.email }}</h2>
                    <p>Date of Birth: {{ profile.date_of_birth }}</p>
                </div>
            </div>
        </div>
    </article>

    <article>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h5 class="bio">BIO</h5>
                    <hr>
                    <p>{{ profile.display_bio|markdown }}</p>
                    <hr>
                    {% if profile.city %}
                        <p>City: {{ profile.city }}</p>
                    {% endif %}
                    {% if profile.state %}
                        <p>State: {{ profile.state }}</p>
                    {% endif %}
                    {% if profile.country_of_residence %}
                        <p>Country: {{ profile.country_of_residence }}</p>
                    {% endif %}
                    {% if profile.favorite_animal %}
                        <p>Animal: {{ profile.favorite_animal }}</p>
                    {% endif %}
                    {% if profile.hobby %}
                        <p>Hobby: {{ profile.hobby }}</p>
                    {% endif %}
                </div>
            </div>
        </div>
    </article>

    <a href="{% url 'profiles:edit-profile' profile.slug %}" class="button">Edit</a>
    <a href="{% url 'profiles:change-password' profile.slug %}" class="button">Change Password</a>

{% endblock %}



 {% if profiles %}
        {% for profile in profiles %}
 {% if profile.avatar %}
                        <img height="50px" src="{{ profile.avatar.url }}" alt="{{ profile.first_name }} {{ profile.last_name }}">
                    {% endif %}
            <a href="{{ profile.get_absolute_url }}"><h1>{{ profile.first_name }} {{ profile.last_name }}</h1></a>
            <a href="{% url 'profiles:edit-profile' profile.slug %}" class="button">Edit</a>
            <a href="{% url 'profiles:change-password' profile.slug %}" class="button">Change Password</a>
        {% endfor %}
    {% else %}
        <p>No Profile</p>
please sign in or sign up
    {% endif %}