allbachelor/allbachelor/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('', views.index, name="mainpage"),
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls')),
    path('blog/', include('blog.urls')),
    path('about/', views.about, name="about"),
    url(r'^shop/', include(('shop.urls', 'shop'), namespace='shop')),
    path('profiles/', include('profiles.urls')),
    path(r'markdownx/', include('markdownx.urls')),
    path('order/', include('order.urls')),
    path('tfidf/', include('tfidf.urls')),
    path('matrixfactorization/', include('matrixfactorization.urls')),




]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

allbachelor/blog/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.index, name="bloghome"),
]

allbachelor/order/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('shopcart', views.shop_cart_list, name='shopcart'),
    path('addtocart/<int:product_id>', views.shop_cart_add, name='addtocart'),
    path('deletefromcart/<int:id>', views.shop_cart_delete, name='deletefromcart'),
    path('detail/<int:id>', views.order_detail, name='orderdetail'),
    path('checkout', views.shop_cart_checkout, name='checkout'),
]

allbachelor/order/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.forms import ModelForm, TextInput

from shop.models import Product


class ShopCart(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    product = models.OneToOneField(Product, on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField()

    def __str__(self):
        return self.product

    @property
    def amount(self):
        return (self.quantity * self.product.discount_price)


class ShopCartForm(ModelForm):
    class Meta:
        model = ShopCart
        fields = ['quantity']
        widgets = {
            'quantity': TextInput(attrs={'class': 'input', 'type': 'number', 'value': '1'}),
        }


class Order(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Accepted', 'Accepted'),
        ('Preaparing', 'Preaparing'),
        ('OnShipping', 'OnShipping'),
        ('Completed', 'Completed'),
        ('Canceled', 'Canceled'),
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=10)
    surname = models.CharField(max_length=10)
    address = models.CharField(max_length=150)
    city = models.CharField(max_length=20)
    phone = models.CharField(max_length=20)
    total = models.FloatField()
    note = models.TextField(null=True, default="")
    status = models.CharField(choices=STATUS, default='New', max_length=15)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = ['name', 'surname', 'address', 'city', 'phone']
        widgets = {
            'name': TextInput(attrs={'class': 'input'}),
            'surname': TextInput(attrs={'class': 'input'}),
            'address': TextInput(attrs={'class': 'input'}),
            'city': TextInput(attrs={'class': 'input'}),
            'phone': TextInput(attrs={'class': 'input'}),
        }


class OrderDetail(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    # quantity = models.IntegerField()
    price = models.FloatField()
    total = models.FloatField()
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product

allbachelor/order/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from django.db.models import Sum
from django.forms import ModelForm
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse

from .models import ShopCart, ShopCartForm, OrderForm, Order, OrderDetail


# Create your views here.
@login_required(login_url='/shop/login')
def index(request):
    current_user = request.user
    orders = Order.objects.all().filter(user_id=current_user.id)

    context = {'page': 'orders',
               'orders': orders,
               }
    return render(request, 'order_list.html', context)


@login_required(login_url='/shop/login')
def shop_cart_list(request):
    current_user = request.user
    shopcart = ShopCart.objects.all().filter(user_id=current_user.id)
    carttotal = 0
    for rs in shopcart:
        carttotal += rs.quantity * rs.product.discount_price
    carttax = (14/100)*carttotal
    cartwithtax= carttotal+carttax

    context = {'page': 'cart',
               'shopcart': shopcart,
               'carttotal': carttotal,
               'carttax':carttax,
               'cartwithtax':cartwithtax
               }
    return render(request, 'shop_cart_list.html', context)


@login_required(login_url='/shop/login')
def shop_cart_add(request, product_id):
    # if this is a POST request we need to process the form data
    url = request.META.get('HTTP_REFERER')  #
    # return HttpResponse(url)
    form = ShopCartForm(request.POST or None)
    if request.method == 'POST':
        # check whether it's valid:
        if form.is_valid():
            current_user = request.user  # Get User id
            quantity = form.cleaned_data['quantity']  # get product quantity from form

            # Checking product in ShopCart
            try:
                q1 = ShopCart.objects.get(user_id=current_user.id, product_id=product_id)
            except ShopCart.DoesNotExist:
                q1 = None
            if q1 != None:  # Update  quantity to exist product quantity
                q1.quantity = q1.quantity + quantity
                q1.save()
            else:  # Add new item to shop cart
                data = ShopCart(user_id=current_user.id, product_id=product_id, quantity=quantity)
                data.save()
            request.session['cart_items'] = ShopCart.objects.filter(
                user_id=current_user.id).count()  # Count item in shop cart
            messages.success(request, "Product added to cart.. ")
            return HttpResponseRedirect(url)

    return HttpResponseRedirect(reverse('shop:product_detail', args=[product_id]))


@login_required(login_url='/shop/login')
def shop_cart_delete(request, id):
    url = request.META.get('HTTP_REFERER')  # Bir önceki adresi alır
    ShopCart.objects.filter(id=id).delete()
    messages.success(request, "Product deleted from  cart.. ")
    return HttpResponseRedirect(url)


@login_required(login_url='/shop/login')
def shop_cart_checkout(request):
    current_user = request.user
    shopcart = ShopCart.objects.all().filter(user_id=current_user.id)
    carttotal = 0
    carttax =0
    cartwithtax =0
    for rs in shopcart:
        carttotal += rs.quantity * rs.product.discount_price
        carttax = (14 / 100) * carttotal
        cartwithtax = carttotal + carttax

    form = OrderForm(request.POST or None)
    if request.method == 'POST':
        # check whether it's valid:
        if form.is_valid():

            # Send Credit card information to bank and get result
            # If payment accepted continue else send payment error to checkout page

            data = Order()
            data.name = form.cleaned_data['name']  # get product quantity from form
            data.surname = form.cleaned_data['surname']
            data.address = form.cleaned_data['address']
            data.city = form.cleaned_data['city']
            data.phone = form.cleaned_data['phone']
            data.to = form.cleaned_data['name']
            data.user_id = current_user.id
            data.total = carttotal
            data.save()

            # Save Shopcart items to Order detail items
            for rs in shopcart:
                detail = OrderDetail()
                detail.order_id = data.id  # Order Id
                detail.product_id = rs.product_id
                detail.user_id = current_user.id
                # detail.quantity = rs.quantity
                detail.price = rs.product.price
                detail.total = rs.amount
                detail.save()
                #  Reduce product Amount  (quantity)

            ShopCart.objects.filter(user_id=current_user.id).delete()  # Clear & Delete shopcart
            request.session['cart_items'] = 0
            messages.success(request, "Order has been completed. Thank You ")
            return HttpResponseRedirect("/order")

    context = {'page': 'checkout',
               'shopcart': shopcart,
               'carttax':carttax,
               'cartwithtax':cartwithtax,
               'carttotal': carttotal,
               }
    return render(request, 'shop_cart_checkout.html', context)


@login_required(login_url='/shop/login')
def order_detail(request, id):
    order = Order.objects.get(pk=id)
    items = OrderDetail.objects.all().filter(order=id)

    context = {'page': 'detail',
               'order': order,
               'items': items,
               }
    return render(request, 'order_detail.html', context)

allbachelor/order/templates/ShopCart.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<h1>Books</h1>

<table border="1">
<thead>
    <tr>
    <th>Name</th>
    <th>Pages</th>
    <th>View</th>
    <th>Edit</th>
    <th>Delete</th>
    </tr>
</thead>
<tbody>
    {% for book in object_list %}
    <tr>
    <td>{{ book.product }}</td>
    <td>{{ book.user }}</td>
    <td>{{ book.quantity }}</td>

    </tr>
    {% endfor %}
</tbody>
</table>



</body>
</html>

allbachelor/order/templates/ShopCart_Add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<h1>Books</h1>
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>



</body>
</html>

allbachelor/order/templates/order_detail.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %} CheckO ut Page{% endblock %}
{% block body %}




                <div class="col-md-8">
                    <div class="billing-details">
                            <table class="shopping-cart-table table">
                                <thead>
                                <tr>
                                    <th>Name</th>   <td>{{ order.name }}</td>
                                <tr>
                                <tr>
                                    <th>Surname</th>   <td>{{ order.surname }}</td>
                                <tr>
                                <tr>
                                    <th>Address</th>   <td>{{ order.address }}</td>
                                <tr>
                                <tr>
                                    <th>City</th>   <td>{{ order.city }}</td>
                                <tr>
                                <tr>
                                    <th>City</th>   <td>{{ order.phone }}</td>
                                <tr>
                                <tr>
                                    <th>Date</th>   <td>{{ order.create_at }}</td>
                                <tr>
                                <tr>
                                    <th>Note</th>   <td>    {{ order.note }}      </td>
                                <tr>
                                <tr>
                                    <th>Status</th>   <td>{{ order.status }} </td>
                                <tr>

                                </thead>

                            </table>
                    </div>
                </div>

                <div class="row">
                    <div class="order-summary clearfix">
                        <div class="section-title">
                            <h3 class="title">Order Review</h3>
                        </div>
                        <table class="shopping-cart-table table">
                            <thead>
                            <tr>
                                <th>Product</th>
                                <th></th>
                                <th class="text-center">Price</th>
                                <th class="text-center">Quantity</th>
                                <th class="text-center">Total</th>
                                <th class="text-right"></th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for rs in items %}
                                <tr>
                                    <td class="thumb"><img src="{{ rs.product.image.url }}" alt=""></td>
                                    <td class="details"> <a href="#">{{ rs.product.name }}</a>    </td>
                                    <td class="price text-center"><strong>$ {{ rs.price }}</strong></td>
                                    <td class="qty text-center"><strong>{{ rs.quantity }}</strong></td>
                                    <td class="total text-center"><strong class="primary-color">$ {{ rs.total }}</strong></td>
                                    <td class="text-right"></td>
                                </tr>
                            {% endfor %}
                            </tbody>

                        </table>

                    </div>






                </div>
                <!-- /row -->
            </div>
            <!-- /container -->
        </div>

{% endblock %}

allbachelor/order/templates/order_list.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %} Shop Cart List{% endblock %}
{% block css %}
<link href="{%static 'shop/css/orderlist.css' %}" rel="stylesheet">


{% endblock %}
{% block body %}

    <!-- BREADCRUMB -->
<div id="demo">
  <center><h1>My orders</h1></center>


  <!-- Responsive table starts here -->
  <!-- For correct display on small screens you must add 'data-title' to each 'td' in your table -->
  <div class="table-responsive-vertical shadow-z-1">
  <!-- Table starts here -->
  <table id="table" class="table table-hover table-mc-light-blue">
      <thead>
        <tr>
          <th>ID</th>
          <th>Full Name</th>
          <th>Date</th>
          <th>mobile number</th>
            <th>city</th>
            <th>Total</th>
            <th>status</th>
            <th>detail</th>
        </tr>
      </thead>
      <tbody>
       {% for rs in orders %}
        <tr>
          <td data-title="ID">{{rs.id}}</td>
          <td data-title="Full Name">{{ rs.name }}  {{ rs.surname }}</td>
            <td>{{rs.create_at}}</td>
            <td>{{ rs.phone }}</td>
            <td>{{ rs.city }}</td>
            <td>Rs. {{ rs.total }}</td>
            <td>{{ rs.status }}</td>
          <td data-title="Link">
            <a href="/order/detail/{{ rs.id }}" target="_blank">Detail</a>
          </td>

{% endfor %}
        </tr>

      </tbody>
    </table>
  </div>






                                </tbody>

                            </table>

                        </div>

                    </div>




                </div>




            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </div>

{% endblock %}

allbachelor/order/templates/shop_cart_checkout.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %} Chec kOut Page{% endblock %}
{% block css %}
<link href="{%static 'shop/css/checkoutform.css' %}" rel="stylesheet">
<link href="{%static 'shop/css/shoppingcart.css' %}" rel="stylesheet">

{% endblock %}
{% block body %}
<div class="content">

  <div class="col-md-2"></div>
  <div class="col-md-4">
    <h3><label>Order details</label></h3>
    <form id="checkout-form" name="order" class="clearfix" method="post">
        {% csrf_token %}
      <div class="form-group">
        <label for="">Name on Card</label>
        <input type="text" name="name" placeholder="Bishal" class="form-control" required id="id_name" value="{{ user.first_name }}" />
      </div>
        <div class="form-group">
        <label for="">SurName on Card</label>
            <input class="form-control" type="text" name="surname" placeholder="Last Name" required id="id_surname" value="{{ user.last_name }}">
      </div>
         <div class="form-group">
        <label for="">Address</label>
         <input class="form-control" type="text" name="address" placeholder="Address" required id="id_address">
      </div>
         <div class="form-group">
        <label for="">City</label>
         <input class="form-control" type="text" name="city" placeholder="City" required id="id_city" />
      </div>

      <div class="form-group">
        <label for="">Contact Number</label>
        <input class="form-control" type="text" name="phone" placeholder="Telephone" required id="id_phone" />
      </div>
      <div class="form-group">
        <label for="">Total payment:</label>
       <input class="input" type="text" name="amount" value="Order Total : ${{ cartwithtax }}" readonly>
      </div>
        <button type="submit" class="btn btn-success ready">
       Ready to buy ?
    </button>
    </form>
  </div>
</div>



            <div class="row">
                <div class="order-summary clearfix">
                    <div class="section-title">
                        <h3 class="title">Order Review</h3>
                    </div>


<!--                 -->




            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </div>
 <div class="cart">
    <ul class="cartWrap">
        {% for rs in shopcart %}
      <li class="items even">
    <div class="infoWrap">
        <div class="cartSection">
        <img src="{{rs.product.image.url}}" alt="" class="itemImg" />
          <p class="itemNumber">#QUE-007544-002</p>
          <h3>{{rs.product.name}}</h3>

           <p> <input type="text"  class="qty" placeholder="{{rs.quantity}}"/>  X <del>Rs.{{rs.product.price}}</del> Rs.{{ rs.product.discount_price }}</p>

        </div>

        <div class="prodTotal cartSection">
          <p class="stockStatus">= Rs. {{ rs.amount }}</p>
        </div>
              <div class="cartSection removeWrap">
           <a href="/order/deletefromcart/{{ rs.id }}" class="remove">x</a>
        </div>
      </div>
      </li>
        {% endfor %}


    </ul>
  </div>

  <div class="promoCode"><label for="promo">Have A Promo Code?</label><input type="text" name="promo" placholder="Enter Code" />
  <a href="#" class="btn"></a></div>

  <div class="subtotal cf">
    <ul>
      <li class="totalRow"><span class="label">Subtotal</span><span class="value">Rs. {{ carttotal }}</span></li>

          <li class="totalRow"><span class="label">Shipping</span><span class="value">Free Shipping</span></li>

            <li class="totalRow"><span class="label">Tax</span><span class="value">{{carttax}}</span></li>
            <li class="totalRow final"><span class="label">Total</span><span class="value">{{cartwithtax }}</span></li>
      <li class="totalRow"><a href="/order/checkout" class="btn continue">Checkout</a></li>
    </ul>
  </div>
</div>


{% endblock %}

allbachelor/order/templates/shop_cart_list.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %} Shop Cart List{% endblock %}
{% block css %}
<link href="{%static 'shop/css/shoppingcart.css' %}" rel="stylesheet">
{% endblock %}
{% block body %}

    <div class="wrap cf">
  <div class="heading cf">
    <h1>My Cart</h1>
    <a href="" class="continue">Continue Shopping</a>
  </div>
  <div class="cart">
    <ul class="cartWrap">
        {% for rs in shopcart %}
      <li class="items even">
    <div class="infoWrap">
        <div class="cartSection">
        <img src="{{rs.product.image.url}}" alt="" class="itemImg" />
          <p class="itemNumber">#QUE-007544-002</p>
          <h3>{{rs.product.name}}</h3>

           <p> <input type="text"  class="qty" placeholder="{{rs.quantity}}"/>  X <del>Rs.{{rs.product.price}}</del> Rs.{{ rs.product.discount_price }}</p>

        </div>

        <div class="prodTotal cartSection">
          <p class="stockStatus">= Rs. {{ rs.amount }}</p>
        </div>
              <div class="cartSection removeWrap">
           <a href="/order/deletefromcart/{{ rs.id }}" class="remove">x</a>
        </div>
      </div>
      </li>
        {% endfor %}


    </ul>
  </div>

  <div class="promoCode"><label for="promo">Have A Promo Code?</label><input type="text" name="promo" placholder="Enter Code" />
  <a href="#" class="btn"></a></div>

  <div class="subtotal cf">
    <ul>
      <li class="totalRow"><span class="label">Subtotal</span><span class="value">Rs. {{ carttotal }}</span></li>

          <li class="totalRow"><span class="label">Shipping</span><span class="value">Free Shipping</span></li>

            <li class="totalRow"><span class="label">Tax</span><span class="value">{{carttax}}</span></li>
            <li class="totalRow final"><span class="label">Total</span><span class="value">{{cartwithtax }}</span></li>
      <li class="totalRow"><a href="/order/checkout" class="btn continue">Checkout</a></li>
    </ul>
  </div>
</div>
{% endblock %}